services:
  kitchen-api:
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      kitchen_db_container:
        condition: service_healthy
        restart: true
    volumes:
      - .:/usr/src/app

  kitchen_db_container:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: kitchen_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 33060:3306
    healthcheck:
      test: ['CMD-SHELL', "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 20s
      start_interval: 3s
