services:
  kitchen-api:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      kitchen_db_container:
        condition: service_healthy
        restart: true
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  kitchen_db_container:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  node_modules:
